### ISSUE TITLE
Add compatibility with Python 2

### ISSUE THREAD

**Issue by aaugustin** [aaugustin/datedelta#2]
Cf. https://twitter.com/aymericaugustin/status/713008267165827072

The README explains what changes are required for running the code on Python 2.

I want to enforce keyword-only arguments in the API and they aren't supported on Python 2. (`kwonly` is overkill here.)

I believe the most elegant solution would be to make these changes on the fly during installation, only on Python 2. If someone wants to extend setup.py to do that, I'll consider a pull request favorably.

Since I'm not planning to use Python 2 again, I don't have any interest in writing that code myself.

**Comment by grantmcconnaughey** [comment]
`2to3` doesn't think there are any changes that need to be made. :frowning: 

```
datedelta $ 2to3 datedelta.py
RefactoringTool: Skipping implicit fixer: buffer
RefactoringTool: Skipping implicit fixer: idioms
RefactoringTool: Skipping implicit fixer: set_literal
RefactoringTool: Skipping implicit fixer: ws_comma
RefactoringTool: No changes to datedelta.py
RefactoringTool: Files that need to be modified:
RefactoringTool: datedelta.py
```

**Comment by aaugustin** [comment]
Thanks for investigating! You need `3to2` here, not `2to3` ;-)

**Comment by grantmcconnaughey** [comment]
Oh for crying out loud, you're right. Thanks. :+1:

**Comment by aaugustin** [comment]
The last person who hit this didn't realize they were using Python 2 rather than Python 3 (see #5).

It really seems best to keep this library Python 3 only.
