### ISSUE TITLE
Error while using at aws ec2

### ISSUE THREAD

**Issue by SaketJNU** [aaugustin/datedelta#5]
Hi,

I was working with **aws ec2 instance** with apache server and flask. I installed **datedelta** by using ``pip install datedelta``. Now, in order to restart the server, it is showing the error as in below image:
![error](https://user-images.githubusercontent.com/20414394/37160010-40199b20-2315-11e8-9074-1ef94da58ee8.jpg)

I have fixed it for my application and will open the PR asap.

Thanks,
Dr. Saket

**Comment by SaketJNU** [comment]
A PR is opened as: https://github.com/aaugustin/datedelta/pull/6/files

**Comment by aaugustin** [comment]
Duplicate of #2.
